dependencies:
  - python=3
  - pip:
    - scapy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - sklearn
    - yfinance
    - tabulate
    - QuantLib
    - cufflinks
    - pandoc
    - xelatex
    - texlive-xetex
    - texlive-fonts-recommended
    - texlive-generic-recommended
