dependencies:
  - python=3
  - pip:
    - scapy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - yfinance
    - tabulate
    - QuantLib
    - cufflinks
    - pandoc
    - jupyter_contrib_nbextensions
    - pyppeteer
    - nbconvert[webpdf]
    - statsmodels
    - shap
    - seaborn
    - xgboost
    - keras
    # - pyfolio
    - pykalman
    - jupyter-resource-usage
    - tensorflow
